name: Update Results JSON

on:
  schedule:
    - cron: '0 11 * * *'  # Corre todos los días a las 11 AM UTC

permissions:
  contents: write

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fix pandas/numpy compatibility
        run: |
          pip uninstall -y numpy pandas
          pip install numpy==1.24.4 pandas==1.5.3

      - name: Run analysis script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python financial_analyst.py

      - name: Copy results to docs
        run: |
          cp results.json docs/results.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results.json docs/results.json
          git commit -m "📅 results.json [$(date)]" || exit 0
          git push
